### ISSUE TITLE
who is the maintainer of this repo?

### ISSUE THREAD

**Issue by psteinb** [swcarpentry/hpc-novice#11]
@jduckles @gvwilson who is the maintainer of this repo? there is some constructive activity currently and I am a bit afraid that so far, no one with contributor permissions has replied to any PR or issue here. Can you please help out?

thanks -
P

**Comment by gvwilson** [comment]
There isn't one yet - do you want to take it on?

**Comment by psteinb** [comment]
I'd do it if I may appoint a deputy or if one is appointed alongside myself ... my time for this could be available in spikes only but I'd do my best not to let anyone down.

**Comment by jduckles** [comment]
We can certainly appoint a deputy, perhaps @shwina would like to be a deputy?

**Comment by jduckles** [comment]
I've just given @psteinb and @shwina merge/write permissions. Let me know if at any time either of you want this responsibility revoked or transferred 😁.

**Comment by psteinb** [comment]
@jduckles looking at the existing PRs, I still am unable to merge. :/

**Comment by jduckles** [comment]
Ok, I changed you to an admin on the repo. Does that work now?

**Comment by jduckles** [comment]
You haven't accepted the invitation to join the team, so you're not on it yet apparently.

**Comment by psteinb** [comment]
I joined the team now. I guess that was it. I can merge now. Thanks for pointing me to that.

**Comment by jduckles** [comment]
Great!
