### ISSUE TITLE
choice of scheduler

### ISSUE THREAD

**Issue by psteinb** [swcarpentry/hpc-novice#12]
@zonca wondered which scheduler to aim for. I'd vote for starting with SLURM as the majority of systems I am able to use run on it. I personally would volunteer to convert the slurm commands to other batch systems. I have access to a PBS and a LSF system.

technically, I'd be nice to have some (javascript?) magic available as [the Apache Spark docs](http://spark.apache.org/docs/latest/quick-start.html) have (check out how one can switch between the Scala version of the example codes and the python version).

**Comment by dbrunson** [comment]
If we could figure out a way to make the scheduler choice (and queue names, walltime limits, and other policies of scheduling) be easily edited to be site specific that would be great.

**Comment by psteinb** [comment]
maybe this could be done with a pandoc filter? [Makefile#L53](https://github.com/swcarpentry/hpc-novice/blob/gh-pages/Makefile#L53) I am not so versed with pandoc.

**Comment by psteinb** [comment]
on another thought, how about starting to create material based on slurm (using the default queue und default walltime) and adding the drop-in choice for other schedulers later?

**Comment by dbrunson** [comment]
Sounds like a good place to start.  (And we use torque locally, so I'm not being self-serving :))

**Comment by psteinb** [comment]
ok, then I'll start with SLURM/LSF and think about the pandoc filter idea.
