### ISSUE TITLE
Some work at The University of Colorado on Basics of Supercomputing

### ISSUE THREAD

**Issue by jduckles** [swcarpentry/hpc-novice#13]
@knuths has shared with me some lessons on Basics of Supercomputing from the University of Colorado. The licensing is unclear to me, but I know Shelly has intent to participate in a community HPC Carpentry lesson. So I wanted to ping her and bring her thoughts into this repo.

https://github.com/ResearchComputing/Final_Tutorials/tree/master/Basics_Supercomputing

**Comment by knuths** [comment]
Haven't had a chance to attach any official licensing, but totally for free and open use.  We're hosting another in January and will have updated slides.  Would love to help out with the project you all are doing!

**Comment by psteinb** [comment]
hi there, thanks for sharing this. I'll declare this as a possible enhancement of the materials to come. 
@jduckles would it be ok to close this issue then?

**Comment by jduckles** [comment]
Sure.

**Comment by jduckles** [comment]
Looks like the original link has rotted. I think its here now. 
https://github.com/ResearchComputing/Final_Tutorials/tree/master/Parallel_Topics/Beginner_Parallel
