### ISSUE TITLE
merging new lesson template in

### ISSUE THREAD

**Issue by psteinb** [swcarpentry/hpc-novice#15]
hi to all, I was wondering if someone could merge the most recent swc lesson template in or at least give me a hand in doing so? if people have some layout templates at hand that they would love to share, feel free to submit PRs.

**Comment by psteinb** [comment]
due to the silence, I assume that everyone is fine with me doing it

**Comment by psteinb** [comment]
see #16

**Comment by shwina** [comment]
Can be closed
