### ISSUE TITLE
milestone added and how to move forward?

### ISSUE THREAD

**Issue by psteinb** [swcarpentry/hpc-novice#19]
dear all, especially @jduckles and @shwina,

I am opening this issue to collect some feedback. As you might have spotted, I added a milestone as I've been asked to perform a workshop of this kind end of March in Germany. Given that 

1) I am trying to be a good community member and hence do refrain from merging my own PRs
2) people might be less interested in contributing while I am driving the material forward

I was wondering how to move forward. I personally see 3 possible directions (feel free to add more):

a) I'll develop the material for the above mentioned milestone in my forked repo of `hpc-novice` and after completion create a huge PR
b) I'll continue pushing a material into a branch of this repo dedicated to the milestone
c) I get your permission to move ahead, push everything I do to gh-pages and we'll review the material later on

I'd appreciate a rather swift response.
Thanks -

**Comment by ChristinaLK** [comment]
Based on the time constraint you're under I'd vote for 1, and then we can either accept that PR and edit from there or use it as a jumping off point.

**Comment by psteinb** [comment]
Hi @ChristinaLK - thanks for getting back to me. As you are a member of 
the steering committee, I'd take this as the way forward if nobody else 
intervenes.

**Comment by dbrunson** [comment]
+1 for "a)"  or is it "1"?  (Same as what @ChristinaLK recommended.)

**Comment by psteinb** [comment]
yes, I think you wanted to say that you thanked me for 1) and suggest a). :)

**Comment by psteinb** [comment]
I'll get started then and the remote branch will be [psteinb/hpc-novice/tree/parallelcon2017](https://github.com/psteinb/hpc-novice/tree/parallelcon2017). I'll keep #18 open for now as I think this would be a good step forward for this repo.

**Comment by jduckles** [comment]
@psteinb Thank you for your enthusiasm here. I agree with @dbrunson and @ChristinaLK we should let you be expedient now, but work to align your work as a contribution later on. There is a lot of interest growing for this lesson in many areas, so I think we'll have a rich conversation about what will and won't be included in a target 2-day novice lesson. Please do let us know how your workshops goes! The more a lesson gets taught by more instructors, the better it can reach the learner.
