### ISSUE TITLE
404 for https://swcarpentry.github.io/hpc-novice/

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/hpc-novice#21]

**Comment by psteinb** [comment]
thanks @rgaiacs, I was under the impression that as this repo basically has no content and a prototype is developed [here](https://github.com/psteinb/hpc-in-a-day), there is no read to render the contents to the address you suggested.

**Comment by rgaiacs** [comment]
Can you remove https://github.com/swcarpentry/hpc-novice/blob/gh-pages/.nojekyll? It will solve this issue. Thanks in advance.

**Comment by psteinb** [comment]
I know about this. That still doesn't answer my concerns from above. At 
the end, people will see a website with no content. Is that the right 
message to convey for swc?

**Comment by rgaiacs** [comment]
> At the end, people will see a website with no content. Is that the right message to convery for swc?

So maybe add some information on the README or at GitHub's repository description stating that?

**Comment by psteinb** [comment]
If that is fine with SWC folks, I have no problem doing that. How do @shwina and/or @ChristinaLK think about it?

**Comment by ChristinaLK** [comment]
I would actually let the site be up, but add a disclaimer to the front page saying that work is still in progress.  I'll submit a PR right now that does that.  

#22

**Comment by shwina** [comment]
Close?

**Comment by psteinb** [comment]
I think this is solved by #22.
