### ISSUE TITLE
Shell basics example

### ISSUE THREAD

**Issue by shwina** [swcarpentry/hpc-novice#32]
Here's a `shell-basics` I have written for an introductory hpc/genomics workshop. Feedback is welcome.

https://clemsonciti.github.io/genomics-workshop/01-shell-basics/

**Comment by psteinb** [comment]
it looks very dense. what were your experiences with it in terms of 
teaching speed?

In terms of contents, it appears to be a good match for hpc-novice.

**Comment by shwina** [comment]
I haven't used these materials in practice yet! My feeling is that the materials can be covered in about an hour. 5 minutes of teaching followed by 5 minutes of exercise (5 exercises), with some leeway for questions.

**Comment by ChristinaLK** [comment]
Looks good!  I would probably have a few comments/suggestions if submitted as a PR but the content looks right.

**Comment by shwina** [comment]
Thanks, @ChristinaLK @psteinb. I've opened PR #33 to motivate further discussion.

**Comment by psteinb** [comment]
I suggest to close this issue and focus the discussion on #33. Please reopen it if desired.
