### ISSUE TITLE
Reference: container training materials

### ISSUE THREAD

**Issue by ChristinaLK** [swcarpentry/hpc-novice#37]
Please add!

**Comment by psteinb** [comment]
I think anything container related should go into a seperate repo. 
Working with modules with be hard already within this content. 
Introducing containers might be might blowing for the learners in a more 
negative sense. Feel free to gather material here about the subject and 
I agree it's getting ever more important in HPC. But I feel we shouldn't 
overload the content of this repo.

Feedback?

**Comment by shwina** [comment]
Agree with @psteinb. Containers are a topic separate from HPC. I could imagine containers being part of a workshop on something like Reproducible Research. But for learners that may have never seen a command-line before, containers are far out of the scope of this introduction.

**Comment by ChristinaLK** [comment]
Totally agree -- I thought we could collect here + then spin off a different repository.  But if it would make sense to go ahead and create a repo, that would be cool too.

**Comment by dbrunson** [comment]
I agree with everyone about it being outside the scope of hpc-novice at this point in time.  But it also might be premature to create a whole repo for it.

**Comment by jduckles** [comment]
I still remember going to OSCON, seeing a presentation about this thing called Docker and running back to the local HPC guys to shouting "This changes everything!" only to see blank faces as I tried to explain it. There is a significant amount of cognitive load in unpacking what they are and why you should care. So yeah, important, but a distraction to the core novice concepts probably.

**Comment by psteinb** [comment]
By means of the singularity project, containers are seeing more and more adoption in HPC. Still, as Jonah pointed out, HPC folks tend to be conservative at points (for a good reason sometimes) and hence there is still some way to go before singularity is is a given on a cluster similar to the module system. I agree with ashwin that containers in academia are pitched more towards reproducibility...while I think at the same time they have the great potential to foster bad software design.

**Comment by shwina** [comment]
@ChristinaLK can we close this one?

**Comment by ChristinaLK** [comment]
yep.
