### ISSUE TITLE
Possibly cover qbatch

### ISSUE THREAD

**Issue by gdevenyi** [swcarpentry/hpc-novice#5]
@pipitone and I have been developing a serial farming tool which is cluster-type independent for serial farming.

https://github.com/pipitone/qbatch

Plugs right into the ideas of simple pipelining from shell-novice

Supports SGE and PBS so far, LSF in testing.

PRs also welcome of course for other cluster systems (I have plans for XCode, Slurm)

**Comment by psteinb** [comment]
I am trying to revive this repo, so let me reply to this. I would vote NOT to use higher level abstractions like [qbatch](https://github.com/pipitone/qbatch), [snakemake](https://bitbucket.org/snakemake/snakemake/wiki/Home) and others in this lesson. While they offer a great productivity boost for those they can use them, I think they might be too overwhelming for the target audience of this lesson.

**Comment by gdevenyi** [comment]
Well, snakemake and qbatch are pretty different.

qbatch is designed explicitly as an abstraction layer to take a list of command-line calls and push them onto a cluster without knowing much about the cluster. You can write a for loop, make it echo, and pipe it to qbatch and off to the cluster it goes. snakemake looks more like a make system with cluster integration and targets and other things.

**Comment by psteinb** [comment]
Gabriel,
don't get me wrong on this, from a broad perspective, I think snakemake 
and qbatch offer an abstraction to the batch system. therefor, I don't 
see them becoming an integral part of this lesson. Feel free to disagree.

IMO, both should go into a part of this repo dedicated to "where to go 
from here". I am simply quite careful to expose novice learners to a 
tool which they appreciate only after they know the batch system and the 
involved workflow to submit a lot of similar jobs or to automate submission.

**Comment by ChristinaLK** [comment]
I'll echo @psteinb here: it may seem straightforward to hand people a tool that seamlessly parallelizes their work, but I think the value of a workshop like this is to actually introduce people to *some* of the basics under the hood: how a cluster is structured, the paradigm of job submission, what parallel submission means, how to interact with a scheduler, etc.  

I think there's a fine line between "removing unnecessary complexity" and "introducing a different version of abstraction." :P

It's a cool tool though!  Here at UW Madison we actually have a dedicated system for independently parallel jobs (the situation where you might use qbatch) and it's amenable to many workflows.

**Comment by gdevenyi** [comment]
Okay.
