### ISSUE TITLE
reviving this repo?

### ISSUE THREAD

**Issue by psteinb** [swcarpentry/hpc-novice#7]
I send a [message](http://lists.software-carpentry.org/pipermail/discuss/2016-December/004912.html) to swcarpentry Discuss to infer if the community is still interested in supporting this repo and pushing its contents.

**Comment by dbrunson** [comment]
The closed issue also has relevant history/context/discussion: https://github.com/swcarpentry/hpc-novice/issues/4

**Comment by dbrunson** [comment]
Another related effort here: https://github.com/datacarpentry/hpc-carpentry

**Comment by shwina** [comment]
Definitely interested in adding to this repository. I'll add to the list of available reference material by linking to our site's own HPC training materials:

http://clemsonciti.github.io/hpc-workshop/

**Comment by psteinb** [comment]
@dbrunson & @shwina, thanks for contributing to the discussion:
- #4 was a very long discussion with some concluding arguments but IMHO it never reached a critical mass or a direction that culminated into concrete material
- not surprising to see data-carpentry coming into the game, [datacarpentry/hpc-carpentry](https://github.com/datacarpentry/hpc-carpentry) is at the same level than this repo I guess
- [hpc-workshop@clemsonciti](http://clemsonciti.github.io/hpc-workshop/) appears nicely fit in terms of shell intro, remote access, file transfer; however the material is bound to the Palmetto cluster and I am missing the narrative a bit at the end (submitting sleep jobs?); I'd personally think that the some of the material on the shell could be copied into this repo with permission of the authors. But before thinking about something like this, I wonder who is in charge of this repo?

**Comment by shwina** [comment]
One of the results of #4 was the following document which outlines a vision for an HPC Carpentry workshop, and was submitted to SC '16 - but unfortunately rejected:

https://github.com/swcarpentry/sc16-tutorial-proposal/blob/master/final-document.pdf

I agree that [hpc-workshop@clemsonciti](http://clemsonciti.github.io/hpc-workshop) can do with a lot more work. It is developed by myself and a few others at Clemson University, and we teach it along with [linux-workshop@clemsonciti](http://clemsonciti.github.io/linux-workshop) each month.

**Comment by psteinb** [comment]
thanks everyone for showing interest so far. I'll close this issue for now and wish everyone a lot of creativity while commenting on PRs to come or sending some on their own.
