### ISSUE TITLE
target audience?

### ISSUE THREAD

**Issue by psteinb** [swcarpentry/hpc-novice#8]
what is the target audience for this lesson? 

for me it's the same target audience as any other swcarpentry-novice courses, namely those learners that need the content. I'd assume nothing about them. prior knowledge about using the terminal is beneficial but not required.

of course this question is tightly bound to what this course should teach.

**Comment by shwina** [comment]
IMO, the audience is grad students/researchers that:

* already write and run domain-specific software on "smaller" computers, and now need to scale up/out, or
* need to learn how to use HPC resources to run some domain-specific software which can simply not be run on smaller computers

**Comment by psteinb** [comment]
very well put, I'd not exclude industry specialists. FWIW, HPC is starting to gain traction in SMEs of some domains. At best,  this should go into a .md file, in order to get going.

**Comment by shwina** [comment]
On it.

**Comment by psteinb** [comment]
@shwina I am ramping up my time allocation to this project again. thanks for the contribution.
